name: Example Central Gateway ECU
model: CGW-4P-100T1
firmware_version: 2.1.0-rc3
port_count: 4
ports:
- port_id: 0
  interface_name: eth0
  mac_address: 02:00:00:00:00:01
  speed_mbps: 100
  vlan_membership:
  - 1
  pvid: 1
  is_trunk: false
- port_id: 1
  interface_name: eth1
  mac_address: 02:00:00:00:00:02
  speed_mbps: 100
  vlan_membership:
  - 1
  pvid: 1
  is_trunk: false
- port_id: 2
  interface_name: eth2
  mac_address: 02:00:00:00:00:03
  speed_mbps: 100
  vlan_membership:
  - 1
  pvid: 1
  is_trunk: false
- port_id: 3
  interface_name: eth3
  mac_address: 02:00:00:00:00:04
  speed_mbps: 100
  vlan_membership:
  - 1
  pvid: 1
  is_trunk: false
max_mac_table_size: 1024
mac_aging_time_s: 300
supports_double_tagging: true
supports_gptp: true
can_reset: true
